print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")
print("dasjkdaskldkasldas")